services:
  angular-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '5173:5173'
    develop:
      watch:
        - action: sync
          path: .
          target: /app

  angular-prod:
    build:
      context: .
      dockerfile: Dockerfile
    image: shell
    ports:
      - '8080:8080'

  angular-test:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: test
